"""'add declined_at to family_invites'

Revision ID: 13861325bacf
Revises: 95844ef3641f
Create Date: 2026-06-23 22:13:01.874939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13861325bacf'
down_revision: Union[str, Sequence[str], None] = '95844ef3641f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_invites', schema=None) as batch_op:
        batch_op.drop_column('declined_at')

    # ### end Alembic commands ###
