"""'add family_invites'

Revision ID: 95844ef3641f
Revises: bb79d1d4eacb
Create Date: 2026-06-23 20:26:56.809777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95844ef3641f'
down_revision: Union[str, Sequence[str], None] = 'bb79d1d4eacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('simple_mode', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_invites_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invites_token'))

    op.drop_table('family_invites')
    # ### end Alembic commands ###
